package com.mobnetic.coinguardian.model.market;

import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;

import org.json.JSONArray;
import org.json.JSONObject;

import com.mobnetic.coinguardian.model.CheckerInfo;
import com.mobnetic.coinguardian.model.CurrencyPairInfo;
import com.mobnetic.coinguardian.model.Market;
import com.mobnetic.coinguardian.model.Ticker;
import com.mobnetic.coinguardian.model.currency.VirtualCurrency;

public class AllCrypt extends Market {

	private final static String NAME = "AllCrypt";
	private final static String TTS_NAME = NAME;
	private final static String URL = "https://www.allcrypt.com/api?method=singlemarketdata&marketid=%1$s";
	private final static String URL_CURRENCY_PAIRS = "https://www.allcrypt.com/api?method=marketdatav2";
	private final static HashMap<String, CharSequence[]> CURRENCY_PAIRS = new LinkedHashMap<String, CharSequence[]>();
	private final static HashMap<String, Integer> CURRENCY_PAIRS_IDS = new HashMap<String, Integer>();
	static {
		CURRENCY_PAIRS.put(VirtualCurrency._2CH, new String[]{ VirtualCurrency.BTC, VirtualCurrency.DOGE, VirtualCurrency.LTC });
		CURRENCY_PAIRS.put(VirtualCurrency.ANI, new String[]{ VirtualCurrency.BTC, VirtualCurrency.DOGE, VirtualCurrency.LTC });
		CURRENCY_PAIRS.put(VirtualCurrency.ATO, new String[]{ VirtualCurrency.BTC, VirtualCurrency.DOGE, VirtualCurrency.LTC });
		CURRENCY_PAIRS.put(VirtualCurrency.AUR, new String[]{ VirtualCurrency.BTC, VirtualCurrency.DOGE, VirtualCurrency.LTC });
		CURRENCY_PAIRS.put(VirtualCurrency.AUS, new String[]{ VirtualCurrency.BTC, VirtualCurrency.LTC, VirtualCurrency.DOGE });
		CURRENCY_PAIRS.put(VirtualCurrency.BAC, new String[]{ VirtualCurrency.BTC, VirtualCurrency.DOGE, VirtualCurrency.LTC });
		CURRENCY_PAIRS.put(VirtualCurrency.BAT, new String[]{ VirtualCurrency.BTC, VirtualCurrency.DOGE, VirtualCurrency.LTC });
		CURRENCY_PAIRS.put(VirtualCurrency.BC, new String[]{ VirtualCurrency.BTC, VirtualCurrency.DOGE, VirtualCurrency.LTC });
		CURRENCY_PAIRS.put(VirtualCurrency.BCX, new String[]{ VirtualCurrency.BTC, VirtualCurrency.DOGE, VirtualCurrency.LTC });
		CURRENCY_PAIRS.put(VirtualCurrency.BEK, new String[]{ VirtualCurrency.BTC, VirtualCurrency.DOGE, VirtualCurrency.LTC });
		CURRENCY_PAIRS.put(VirtualCurrency.BIL, new String[]{ VirtualCurrency.BTC, VirtualCurrency.DOGE, VirtualCurrency.LTC });
		CURRENCY_PAIRS.put(VirtualCurrency.BTC, new String[]{ VirtualCurrency.DOGE, VirtualCurrency.LTC });
		CURRENCY_PAIRS.put(VirtualCurrency.BTCS, new String[]{ VirtualCurrency.BTC, VirtualCurrency.DOGE, VirtualCurrency.LTC });
		CURRENCY_PAIRS.put(VirtualCurrency.BUR, new String[]{ VirtualCurrency.BTC, VirtualCurrency.DOGE, VirtualCurrency.LTC });
		CURRENCY_PAIRS.put(VirtualCurrency.CACH, new String[]{ VirtualCurrency.BTC, VirtualCurrency.DOGE, VirtualCurrency.LTC });
		CURRENCY_PAIRS.put(VirtualCurrency.CGA, new String[]{ VirtualCurrency.BTC, VirtualCurrency.DOGE, VirtualCurrency.LTC });
		CURRENCY_PAIRS.put(VirtualCurrency.CGB, new String[]{ VirtualCurrency.BTC, VirtualCurrency.DOGE, VirtualCurrency.LTC });
		CURRENCY_PAIRS.put(VirtualCurrency.CHA, new String[]{ VirtualCurrency.BTC, VirtualCurrency.DOGE, VirtualCurrency.LTC });
		CURRENCY_PAIRS.put(VirtualCurrency.COMM, new String[]{ VirtualCurrency.BTC, VirtualCurrency.DOGE, VirtualCurrency.LTC });
		CURRENCY_PAIRS.put(VirtualCurrency.CON, new String[]{ VirtualCurrency.BTC, VirtualCurrency.DOGE, VirtualCurrency.LTC });
		CURRENCY_PAIRS.put(VirtualCurrency.CORG, new String[]{ VirtualCurrency.BTC, VirtualCurrency.DOGE, VirtualCurrency.LTC });
		CURRENCY_PAIRS.put(VirtualCurrency.CREA, new String[]{ VirtualCurrency.BTC, VirtualCurrency.DOGE, VirtualCurrency.LTC });
		CURRENCY_PAIRS.put(VirtualCurrency.CTC, new String[]{ VirtualCurrency.BTC, VirtualCurrency.DOGE, VirtualCurrency.LTC });
		CURRENCY_PAIRS.put(VirtualCurrency.DGB, new String[]{ VirtualCurrency.BTC, VirtualCurrency.DOGE, VirtualCurrency.LTC });
		CURRENCY_PAIRS.put(VirtualCurrency.DGC, new String[]{ VirtualCurrency.BTC, VirtualCurrency.DOGE, VirtualCurrency.LTC });
		CURRENCY_PAIRS.put(VirtualCurrency.DIME, new String[]{ VirtualCurrency.BTC, VirtualCurrency.DOGE, VirtualCurrency.LTC });
		CURRENCY_PAIRS.put(VirtualCurrency.DOGE, new String[]{ VirtualCurrency.BTC, VirtualCurrency.LTC });
		CURRENCY_PAIRS.put(VirtualCurrency.DOT, new String[]{ VirtualCurrency.BTC, VirtualCurrency.DOGE, VirtualCurrency.BC, VirtualCurrency.LTC });
		CURRENCY_PAIRS.put(VirtualCurrency.DRK, new String[]{ VirtualCurrency.BTC, VirtualCurrency.DOGE, VirtualCurrency.LTC });
		CURRENCY_PAIRS.put(VirtualCurrency.DUC, new String[]{ VirtualCurrency.BTC, VirtualCurrency.DOGE, VirtualCurrency.LTC });
		CURRENCY_PAIRS.put(VirtualCurrency.EAC, new String[]{ VirtualCurrency.BTC, VirtualCurrency.DOGE, VirtualCurrency.LTC });
		CURRENCY_PAIRS.put(VirtualCurrency.ELC, new String[]{ VirtualCurrency.BTC, VirtualCurrency.DOGE, VirtualCurrency.LTC });
		CURRENCY_PAIRS.put(VirtualCurrency.ETOK, new String[]{ VirtualCurrency.BTC, VirtualCurrency.DOGE, VirtualCurrency.LTC });
		CURRENCY_PAIRS.put(VirtualCurrency.EZC, new String[]{ VirtualCurrency.BTC, VirtualCurrency.DOGE, VirtualCurrency.LTC });
		CURRENCY_PAIRS.put(VirtualCurrency.FLAP, new String[]{ VirtualCurrency.BTC, VirtualCurrency.DOGE, VirtualCurrency.LTC });
		CURRENCY_PAIRS.put(VirtualCurrency.FLC, new String[]{ VirtualCurrency.BTC, VirtualCurrency.DOGE, VirtualCurrency.LTC });
		CURRENCY_PAIRS.put(VirtualCurrency.FLO, new String[]{ VirtualCurrency.BTC, VirtualCurrency.DOGE, VirtualCurrency.LTC });
		CURRENCY_PAIRS.put(VirtualCurrency.FRQ, new String[]{ VirtualCurrency.BTC, VirtualCurrency.DOGE, VirtualCurrency.LTC });
		CURRENCY_PAIRS.put(VirtualCurrency.FRSC, new String[]{ VirtualCurrency.BTC, VirtualCurrency.DOGE, VirtualCurrency.LTC });
		CURRENCY_PAIRS.put(VirtualCurrency.FRX, new String[]{ VirtualCurrency.BTC, VirtualCurrency.DOGE, VirtualCurrency.LTC });
		CURRENCY_PAIRS.put(VirtualCurrency.FST, new String[]{ VirtualCurrency.BTC, VirtualCurrency.DOGE, VirtualCurrency.LTC });
		CURRENCY_PAIRS.put(VirtualCurrency.FTC, new String[]{ VirtualCurrency.BTC, VirtualCurrency.DOGE, VirtualCurrency.LTC });
		CURRENCY_PAIRS.put(VirtualCurrency.FZ, new String[]{ VirtualCurrency.BTC, VirtualCurrency.DOGE, VirtualCurrency.LTC });
		CURRENCY_PAIRS.put(VirtualCurrency.GER, new String[]{ VirtualCurrency.BTC, VirtualCurrency.DOGE, VirtualCurrency.LTC });
		CURRENCY_PAIRS.put(VirtualCurrency.GRA, new String[]{ VirtualCurrency.BTC, VirtualCurrency.DOGE, VirtualCurrency.LTC });
		CURRENCY_PAIRS.put(VirtualCurrency.GRC, new String[]{ VirtualCurrency.BTC, VirtualCurrency.DOGE, VirtualCurrency.LTC });
		CURRENCY_PAIRS.put(VirtualCurrency.H2O, new String[]{ VirtualCurrency.BTC, VirtualCurrency.DOGE, VirtualCurrency.LTC });
		CURRENCY_PAIRS.put(VirtualCurrency.ICN, new String[]{ VirtualCurrency.BTC, VirtualCurrency.DOGE, VirtualCurrency.LTC });
		CURRENCY_PAIRS.put(VirtualCurrency.IFC, new String[]{ VirtualCurrency.BTC, VirtualCurrency.DOGE, VirtualCurrency.LTC });
		CURRENCY_PAIRS.put(VirtualCurrency.KAR, new String[]{ VirtualCurrency.BTC, VirtualCurrency.DOGE, VirtualCurrency.BC, VirtualCurrency.LTC });
		CURRENCY_PAIRS.put(VirtualCurrency.KARM, new String[]{ VirtualCurrency.BTC, VirtualCurrency.DOGE, VirtualCurrency.LTC });
		CURRENCY_PAIRS.put(VirtualCurrency.KDC, new String[]{ VirtualCurrency.BTC, VirtualCurrency.DOGE, VirtualCurrency.LTC });
		CURRENCY_PAIRS.put(VirtualCurrency.LGD, new String[]{ VirtualCurrency.BTC, VirtualCurrency.DOGE, VirtualCurrency.BC, VirtualCurrency.LTC });
		CURRENCY_PAIRS.put(VirtualCurrency.LOT, new String[]{ VirtualCurrency.BTC, VirtualCurrency.DOGE, VirtualCurrency.LTC });
		CURRENCY_PAIRS.put(VirtualCurrency.LOVE, new String[]{ VirtualCurrency.BTC, VirtualCurrency.LTC, VirtualCurrency.DOGE });
		CURRENCY_PAIRS.put(VirtualCurrency.LTC, new String[]{ VirtualCurrency.BTC, VirtualCurrency.DOGE });
		CURRENCY_PAIRS.put(VirtualCurrency.LVC, new String[]{ VirtualCurrency.BTC, VirtualCurrency.DOGE, VirtualCurrency.LTC });
		CURRENCY_PAIRS.put(VirtualCurrency.LYC, new String[]{ VirtualCurrency.BTC, VirtualCurrency.DOGE, VirtualCurrency.LTC });
		CURRENCY_PAIRS.put(VirtualCurrency.MAZA, new String[]{ VirtualCurrency.BTC, VirtualCurrency.DOGE, VirtualCurrency.LTC });
		CURRENCY_PAIRS.put(VirtualCurrency.MEC, new String[]{ VirtualCurrency.BTC, VirtualCurrency.DOGE, VirtualCurrency.LTC });
		CURRENCY_PAIRS.put(VirtualCurrency.MED, new String[]{ VirtualCurrency.BTC, VirtualCurrency.DOGE, VirtualCurrency.LTC });
		CURRENCY_PAIRS.put(VirtualCurrency.MEOW, new String[]{ VirtualCurrency.BTC, VirtualCurrency.DOGE, VirtualCurrency.LTC });
		CURRENCY_PAIRS.put(VirtualCurrency.METH, new String[]{ VirtualCurrency.BTC, VirtualCurrency.DOGE, VirtualCurrency.BC, VirtualCurrency.LTC });
		CURRENCY_PAIRS.put(VirtualCurrency.MINT, new String[]{ VirtualCurrency.BTC, VirtualCurrency.DOGE, VirtualCurrency.LTC });
		CURRENCY_PAIRS.put(VirtualCurrency.MLC, new String[]{ VirtualCurrency.BTC, VirtualCurrency.DOGE, VirtualCurrency.LTC });
		CURRENCY_PAIRS.put(VirtualCurrency.MMC, new String[]{ VirtualCurrency.BTC, VirtualCurrency.DOGE, VirtualCurrency.LTC });
		CURRENCY_PAIRS.put(VirtualCurrency.MOL, new String[]{ VirtualCurrency.BTC, VirtualCurrency.DOGE, VirtualCurrency.LTC });
		CURRENCY_PAIRS.put(VirtualCurrency.MOON, new String[]{ VirtualCurrency.BTC, VirtualCurrency.DOGE, VirtualCurrency.LTC });
		CURRENCY_PAIRS.put(VirtualCurrency.MRS, new String[]{ VirtualCurrency.BTC, VirtualCurrency.LTC, VirtualCurrency.DOGE });
		CURRENCY_PAIRS.put(VirtualCurrency.MYR, new String[]{ VirtualCurrency.BTC, VirtualCurrency.DOGE, VirtualCurrency.LTC });
		CURRENCY_PAIRS.put(VirtualCurrency.NET, new String[]{ VirtualCurrency.BTC, VirtualCurrency.DOGE, VirtualCurrency.LTC });
		CURRENCY_PAIRS.put(VirtualCurrency.NOBL, new String[]{ VirtualCurrency.BTC, VirtualCurrency.DOGE, VirtualCurrency.LTC });
		CURRENCY_PAIRS.put(VirtualCurrency.NUT, new String[]{ VirtualCurrency.BTC, VirtualCurrency.DOGE, VirtualCurrency.BC, VirtualCurrency.LTC });
		CURRENCY_PAIRS.put(VirtualCurrency.NYAN, new String[]{ VirtualCurrency.BTC, VirtualCurrency.DOGE, VirtualCurrency.LTC });
		CURRENCY_PAIRS.put(VirtualCurrency.OFF, new String[]{ VirtualCurrency.BTC, VirtualCurrency.DOGE, VirtualCurrency.LTC });
		CURRENCY_PAIRS.put(VirtualCurrency.OLY, new String[]{ VirtualCurrency.BTC, VirtualCurrency.DOGE, VirtualCurrency.LTC });
		CURRENCY_PAIRS.put(VirtualCurrency.ORCA, new String[]{ VirtualCurrency.BTC, VirtualCurrency.DOGE, VirtualCurrency.LTC });
		CURRENCY_PAIRS.put(VirtualCurrency.PAWN, new String[]{ VirtualCurrency.BTC, VirtualCurrency.DOGE, VirtualCurrency.LTC });
		CURRENCY_PAIRS.put(VirtualCurrency.PD, new String[]{ VirtualCurrency.BTC, VirtualCurrency.DOGE, VirtualCurrency.LTC });
		CURRENCY_PAIRS.put(VirtualCurrency.PIR, new String[]{ VirtualCurrency.BTC, VirtualCurrency.DOGE, VirtualCurrency.LTC });
		CURRENCY_PAIRS.put(VirtualCurrency.PKC, new String[]{ VirtualCurrency.BTC, VirtualCurrency.DOGE, VirtualCurrency.LTC });
		CURRENCY_PAIRS.put(VirtualCurrency.PLC, new String[]{ VirtualCurrency.BTC, VirtualCurrency.DOGE, VirtualCurrency.LTC });
		CURRENCY_PAIRS.put(VirtualCurrency.PMC, new String[]{ VirtualCurrency.BTC, VirtualCurrency.DOGE, VirtualCurrency.LTC });
		CURRENCY_PAIRS.put(VirtualCurrency.POP, new String[]{ VirtualCurrency.BTC, VirtualCurrency.DOGE, VirtualCurrency.LTC });
		CURRENCY_PAIRS.put(VirtualCurrency.POT, new String[]{ VirtualCurrency.BTC, VirtualCurrency.DOGE, VirtualCurrency.LTC });
		CURRENCY_PAIRS.put(VirtualCurrency.PPC, new String[]{ VirtualCurrency.BTC, VirtualCurrency.DOGE, VirtualCurrency.LTC });
		CURRENCY_PAIRS.put(VirtualCurrency.PRC, new String[]{ VirtualCurrency.BTC, VirtualCurrency.DOGE, VirtualCurrency.LTC });
		CURRENCY_PAIRS.put(VirtualCurrency.PRT, new String[]{ VirtualCurrency.BTC, VirtualCurrency.DOGE, VirtualCurrency.LTC });
		CURRENCY_PAIRS.put(VirtualCurrency.PT, new String[]{ VirtualCurrency.BTC, VirtualCurrency.DOGE, VirtualCurrency.LTC });
		CURRENCY_PAIRS.put(VirtualCurrency.PTC, new String[]{ VirtualCurrency.BTC, VirtualCurrency.DOGE, VirtualCurrency.LTC });
		CURRENCY_PAIRS.put(VirtualCurrency.PXC, new String[]{ VirtualCurrency.BTC, VirtualCurrency.DOGE, VirtualCurrency.LTC });
		CURRENCY_PAIRS.put(VirtualCurrency.Q2C, new String[]{ VirtualCurrency.BTC, VirtualCurrency.DOGE, VirtualCurrency.LTC });
		CURRENCY_PAIRS.put(VirtualCurrency.QQC, new String[]{ VirtualCurrency.BTC, VirtualCurrency.DOGE, VirtualCurrency.LTC });
		CURRENCY_PAIRS.put(VirtualCurrency.QRK, new String[]{ VirtualCurrency.BTC, VirtualCurrency.DOGE, VirtualCurrency.LTC });
		CURRENCY_PAIRS.put(VirtualCurrency.RDD, new String[]{ VirtualCurrency.BTC, VirtualCurrency.DOGE, VirtualCurrency.LTC });
		CURRENCY_PAIRS.put(VirtualCurrency.RUP, new String[]{ VirtualCurrency.BTC, VirtualCurrency.DOGE, VirtualCurrency.LTC });
		CURRENCY_PAIRS.put(VirtualCurrency.SLR, new String[]{ VirtualCurrency.BTC, VirtualCurrency.DOGE, VirtualCurrency.BC, VirtualCurrency.LTC });
		CURRENCY_PAIRS.put(VirtualCurrency.SMC, new String[]{ VirtualCurrency.BTC, VirtualCurrency.DOGE, VirtualCurrency.LTC });
		CURRENCY_PAIRS.put(VirtualCurrency.SOC, new String[]{ VirtualCurrency.BTC, VirtualCurrency.DOGE, VirtualCurrency.LTC });
		CURRENCY_PAIRS.put(VirtualCurrency.STL, new String[]{ VirtualCurrency.BTC, VirtualCurrency.DOGE, VirtualCurrency.BC, VirtualCurrency.LTC });
		CURRENCY_PAIRS.put(VirtualCurrency.STP, new String[]{ VirtualCurrency.BTC, VirtualCurrency.LTC, VirtualCurrency.DOGE });
		CURRENCY_PAIRS.put(VirtualCurrency.SXC, new String[]{ VirtualCurrency.BTC, VirtualCurrency.DOGE, VirtualCurrency.LTC });
		CURRENCY_PAIRS.put(VirtualCurrency.TFC, new String[]{ VirtualCurrency.BTC, VirtualCurrency.DOGE, VirtualCurrency.LTC });
		CURRENCY_PAIRS.put(VirtualCurrency.TGC, new String[]{ VirtualCurrency.BTC, VirtualCurrency.DOGE, VirtualCurrency.LTC });
		CURRENCY_PAIRS.put(VirtualCurrency.TIPS, new String[]{ VirtualCurrency.BTC, VirtualCurrency.DOGE, VirtualCurrency.LTC });
		CURRENCY_PAIRS.put(VirtualCurrency.TOP, new String[]{ VirtualCurrency.BTC, VirtualCurrency.DOGE, VirtualCurrency.LTC });
		CURRENCY_PAIRS.put(VirtualCurrency.TTC, new String[]{ VirtualCurrency.BTC, VirtualCurrency.DOGE, VirtualCurrency.LTC });
		CURRENCY_PAIRS.put(VirtualCurrency.UNC, new String[]{ VirtualCurrency.BTC, VirtualCurrency.DOGE, VirtualCurrency.LTC });
		CURRENCY_PAIRS.put(VirtualCurrency.USDE, new String[]{ VirtualCurrency.BTC, VirtualCurrency.DOGE, VirtualCurrency.LTC });
		CURRENCY_PAIRS.put(VirtualCurrency.UTC, new String[]{ VirtualCurrency.BTC, VirtualCurrency.DOGE, VirtualCurrency.LTC });
		CURRENCY_PAIRS.put(VirtualCurrency.VEL, new String[]{ VirtualCurrency.BTC, VirtualCurrency.DOGE, VirtualCurrency.LTC });
		CURRENCY_PAIRS.put(VirtualCurrency.VGC, new String[]{ VirtualCurrency.BTC, VirtualCurrency.DOGE, VirtualCurrency.LTC });
		CURRENCY_PAIRS.put(VirtualCurrency.VMP, new String[]{ VirtualCurrency.BTC, VirtualCurrency.DOGE, VirtualCurrency.LTC });
		CURRENCY_PAIRS.put(VirtualCurrency.VTC, new String[]{ VirtualCurrency.BTC, VirtualCurrency.DOGE, VirtualCurrency.LTC });
		CURRENCY_PAIRS.put(VirtualCurrency.WDC, new String[]{ VirtualCurrency.BTC, VirtualCurrency.DOGE, VirtualCurrency.LTC });
		CURRENCY_PAIRS.put(VirtualCurrency.WTC, new String[]{ VirtualCurrency.BTC, VirtualCurrency.DOGE, VirtualCurrency.LTC });
		CURRENCY_PAIRS.put(VirtualCurrency.XTN, new String[]{ VirtualCurrency.BTC, VirtualCurrency.LTC, VirtualCurrency.DOGE });
		CURRENCY_PAIRS.put(VirtualCurrency.XXL, new String[]{ VirtualCurrency.BTC, VirtualCurrency.DOGE, VirtualCurrency.LTC });
		CURRENCY_PAIRS.put(VirtualCurrency.ZMB, new String[]{ VirtualCurrency.BTC, VirtualCurrency.DOGE, VirtualCurrency.LTC });
		CURRENCY_PAIRS.put(VirtualCurrency.ZTC, new String[]{ VirtualCurrency.BTC, VirtualCurrency.DOGE, VirtualCurrency.LTC });
		CURRENCY_PAIRS_IDS.put("2CH_BTC", 314);
		CURRENCY_PAIRS_IDS.put("2CH_DOGE", 316);
		CURRENCY_PAIRS_IDS.put("2CH_LTC", 315);
		CURRENCY_PAIRS_IDS.put("ANI_BTC", 323);
		CURRENCY_PAIRS_IDS.put("ANI_DOGE", 325);
		CURRENCY_PAIRS_IDS.put("ANI_LTC", 324);
		CURRENCY_PAIRS_IDS.put("ATO_BTC", 182);
		CURRENCY_PAIRS_IDS.put("ATO_DOGE", 184);
		CURRENCY_PAIRS_IDS.put("ATO_LTC", 183);
		CURRENCY_PAIRS_IDS.put("AUR_BTC", 401);
		CURRENCY_PAIRS_IDS.put("AUR_DOGE", 403);
		CURRENCY_PAIRS_IDS.put("AUR_LTC", 402);
		CURRENCY_PAIRS_IDS.put("AUS_BTC", 492);
		CURRENCY_PAIRS_IDS.put("AUS_DOGE", 494);
		CURRENCY_PAIRS_IDS.put("AUS_LTC", 493);
		CURRENCY_PAIRS_IDS.put("BAC_BTC", 209);
		CURRENCY_PAIRS_IDS.put("BAC_DOGE", 271);
		CURRENCY_PAIRS_IDS.put("BAC_LTC", 240);
		CURRENCY_PAIRS_IDS.put("BAT_BTC", 362);
		CURRENCY_PAIRS_IDS.put("BAT_DOGE", 364);
		CURRENCY_PAIRS_IDS.put("BAT_LTC", 363);
		CURRENCY_PAIRS_IDS.put("BCX_BTC", 458);
		CURRENCY_PAIRS_IDS.put("BCX_DOGE", 460);
		CURRENCY_PAIRS_IDS.put("BCX_LTC", 459);
		CURRENCY_PAIRS_IDS.put("BC_BTC", 482);
		CURRENCY_PAIRS_IDS.put("BC_DOGE", 484);
		CURRENCY_PAIRS_IDS.put("BC_LTC", 483);
		CURRENCY_PAIRS_IDS.put("BEK_BTC", 142);
		CURRENCY_PAIRS_IDS.put("BEK_DOGE", 11);
		CURRENCY_PAIRS_IDS.put("BEK_LTC", 111);
		CURRENCY_PAIRS_IDS.put("BIL_BTC", 143);
		CURRENCY_PAIRS_IDS.put("BIL_DOGE", 12);
		CURRENCY_PAIRS_IDS.put("BIL_LTC", 112);
		CURRENCY_PAIRS_IDS.put("BTCS_BTC", 145);
		CURRENCY_PAIRS_IDS.put("BTCS_DOGE", 14);
		CURRENCY_PAIRS_IDS.put("BTCS_LTC", 114);
		CURRENCY_PAIRS_IDS.put("BTC_DOGE", 13);
		CURRENCY_PAIRS_IDS.put("BTC_LTC", 113);
		CURRENCY_PAIRS_IDS.put("BUR_BTC", 428);
		CURRENCY_PAIRS_IDS.put("BUR_DOGE", 430);
		CURRENCY_PAIRS_IDS.put("BUR_LTC", 429);
		CURRENCY_PAIRS_IDS.put("CACH_BTC", 386);
		CURRENCY_PAIRS_IDS.put("CACH_DOGE", 388);
		CURRENCY_PAIRS_IDS.put("CACH_LTC", 387);
		CURRENCY_PAIRS_IDS.put("CGA_BTC", 211);
		CURRENCY_PAIRS_IDS.put("CGA_DOGE", 272);
		CURRENCY_PAIRS_IDS.put("CGA_LTC", 241);
		CURRENCY_PAIRS_IDS.put("CGB_BTC", 212);
		CURRENCY_PAIRS_IDS.put("CGB_DOGE", 273);
		CURRENCY_PAIRS_IDS.put("CGB_LTC", 242);
		CURRENCY_PAIRS_IDS.put("CHA_BTC", 308);
		CURRENCY_PAIRS_IDS.put("CHA_DOGE", 310);
		CURRENCY_PAIRS_IDS.put("CHA_LTC", 309);
		CURRENCY_PAIRS_IDS.put("COMM_BTC", 434);
		CURRENCY_PAIRS_IDS.put("COMM_DOGE", 436);
		CURRENCY_PAIRS_IDS.put("COMM_LTC", 435);
		CURRENCY_PAIRS_IDS.put("CON_BTC", 213);
		CURRENCY_PAIRS_IDS.put("CON_DOGE", 274);
		CURRENCY_PAIRS_IDS.put("CON_LTC", 243);
		CURRENCY_PAIRS_IDS.put("CORG_BTC", 214);
		CURRENCY_PAIRS_IDS.put("CORG_DOGE", 275);
		CURRENCY_PAIRS_IDS.put("CORG_LTC", 244);
		CURRENCY_PAIRS_IDS.put("CREA_BTC", 395);
		CURRENCY_PAIRS_IDS.put("CREA_DOGE", 397);
		CURRENCY_PAIRS_IDS.put("CREA_LTC", 396);
		CURRENCY_PAIRS_IDS.put("CTC_BTC", 176);
		CURRENCY_PAIRS_IDS.put("CTC_DOGE", 178);
		CURRENCY_PAIRS_IDS.put("CTC_LTC", 177);
		CURRENCY_PAIRS_IDS.put("DGB_BTC", 205);
		CURRENCY_PAIRS_IDS.put("DGB_DOGE", 207);
		CURRENCY_PAIRS_IDS.put("DGB_LTC", 206);
		CURRENCY_PAIRS_IDS.put("DGC_BTC", 146);
		CURRENCY_PAIRS_IDS.put("DGC_DOGE", 15);
		CURRENCY_PAIRS_IDS.put("DGC_LTC", 115);
		CURRENCY_PAIRS_IDS.put("DIME_BTC", 374);
		CURRENCY_PAIRS_IDS.put("DIME_DOGE", 376);
		CURRENCY_PAIRS_IDS.put("DIME_LTC", 375);
		CURRENCY_PAIRS_IDS.put("DOGE_BTC", 1);
		CURRENCY_PAIRS_IDS.put("DOGE_LTC", 2);
		CURRENCY_PAIRS_IDS.put("DOT_BC", 487);
		CURRENCY_PAIRS_IDS.put("DOT_BTC", 476);
		CURRENCY_PAIRS_IDS.put("DOT_DOGE", 478);
		CURRENCY_PAIRS_IDS.put("DOT_LTC", 477);
		CURRENCY_PAIRS_IDS.put("DRK_BTC", 215);
		CURRENCY_PAIRS_IDS.put("DRK_DOGE", 277);
		CURRENCY_PAIRS_IDS.put("DRK_LTC", 245);
		CURRENCY_PAIRS_IDS.put("DUC_BTC", 216);
		CURRENCY_PAIRS_IDS.put("DUC_DOGE", 278);
		CURRENCY_PAIRS_IDS.put("DUC_LTC", 246);
		CURRENCY_PAIRS_IDS.put("EAC_BTC", 198);
		CURRENCY_PAIRS_IDS.put("EAC_DOGE", 197);
		CURRENCY_PAIRS_IDS.put("EAC_LTC", 196);
		CURRENCY_PAIRS_IDS.put("ELC_BTC", 147);
		CURRENCY_PAIRS_IDS.put("ELC_DOGE", 17);
		CURRENCY_PAIRS_IDS.put("ELC_LTC", 116);
		CURRENCY_PAIRS_IDS.put("ETOK_BTC", 398);
		CURRENCY_PAIRS_IDS.put("ETOK_DOGE", 400);
		CURRENCY_PAIRS_IDS.put("ETOK_LTC", 399);
		CURRENCY_PAIRS_IDS.put("EZC_BTC", 217);
		CURRENCY_PAIRS_IDS.put("EZC_DOGE", 279);
		CURRENCY_PAIRS_IDS.put("EZC_LTC", 247);
		CURRENCY_PAIRS_IDS.put("FLAP_BTC", 218);
		CURRENCY_PAIRS_IDS.put("FLAP_DOGE", 280);
		CURRENCY_PAIRS_IDS.put("FLAP_LTC", 248);
		CURRENCY_PAIRS_IDS.put("FLC_BTC", 410);
		CURRENCY_PAIRS_IDS.put("FLC_DOGE", 412);
		CURRENCY_PAIRS_IDS.put("FLC_LTC", 411);
		CURRENCY_PAIRS_IDS.put("FLO_BTC", 455);
		CURRENCY_PAIRS_IDS.put("FLO_DOGE", 457);
		CURRENCY_PAIRS_IDS.put("FLO_LTC", 456);
		CURRENCY_PAIRS_IDS.put("FRQ_BTC", 219);
		CURRENCY_PAIRS_IDS.put("FRQ_DOGE", 281);
		CURRENCY_PAIRS_IDS.put("FRQ_LTC", 249);
		CURRENCY_PAIRS_IDS.put("FRSC_BTC", 148);
		CURRENCY_PAIRS_IDS.put("FRSC_DOGE", 18);
		CURRENCY_PAIRS_IDS.put("FRSC_LTC", 117);
		CURRENCY_PAIRS_IDS.put("FRX_BTC", 470);
		CURRENCY_PAIRS_IDS.put("FRX_DOGE", 472);
		CURRENCY_PAIRS_IDS.put("FRX_LTC", 471);
		CURRENCY_PAIRS_IDS.put("FST_BTC", 149);
		CURRENCY_PAIRS_IDS.put("FST_DOGE", 19);
		CURRENCY_PAIRS_IDS.put("FST_LTC", 118);
		CURRENCY_PAIRS_IDS.put("FTC_BTC", 220);
		CURRENCY_PAIRS_IDS.put("FTC_DOGE", 282);
		CURRENCY_PAIRS_IDS.put("FTC_LTC", 250);
		CURRENCY_PAIRS_IDS.put("FZ_BTC", 150);
		CURRENCY_PAIRS_IDS.put("FZ_DOGE", 20);
		CURRENCY_PAIRS_IDS.put("FZ_LTC", 119);
		CURRENCY_PAIRS_IDS.put("GER_BTC", 479);
		CURRENCY_PAIRS_IDS.put("GER_DOGE", 481);
		CURRENCY_PAIRS_IDS.put("GER_LTC", 480);
		CURRENCY_PAIRS_IDS.put("GRA_BTC", 356);
		CURRENCY_PAIRS_IDS.put("GRA_DOGE", 358);
		CURRENCY_PAIRS_IDS.put("GRA_LTC", 357);
		CURRENCY_PAIRS_IDS.put("GRC_BTC", 151);
		CURRENCY_PAIRS_IDS.put("GRC_DOGE", 21);
		CURRENCY_PAIRS_IDS.put("GRC_LTC", 120);
		CURRENCY_PAIRS_IDS.put("H2O_BTC", 389);
		CURRENCY_PAIRS_IDS.put("H2O_DOGE", 391);
		CURRENCY_PAIRS_IDS.put("H2O_LTC", 390);
		CURRENCY_PAIRS_IDS.put("ICN_BTC", 326);
		CURRENCY_PAIRS_IDS.put("ICN_DOGE", 328);
		CURRENCY_PAIRS_IDS.put("ICN_LTC", 327);
		CURRENCY_PAIRS_IDS.put("IFC_BTC", 152);
		CURRENCY_PAIRS_IDS.put("IFC_DOGE", 22);
		CURRENCY_PAIRS_IDS.put("IFC_LTC", 121);
		CURRENCY_PAIRS_IDS.put("KARM_BTC", 153);
		CURRENCY_PAIRS_IDS.put("KARM_DOGE", 23);
		CURRENCY_PAIRS_IDS.put("KARM_LTC", 122);
		CURRENCY_PAIRS_IDS.put("KAR_BC", 485);
		CURRENCY_PAIRS_IDS.put("KAR_BTC", 413);
		CURRENCY_PAIRS_IDS.put("KAR_DOGE", 415);
		CURRENCY_PAIRS_IDS.put("KAR_LTC", 414);
		CURRENCY_PAIRS_IDS.put("KDC_BTC", 221);
		CURRENCY_PAIRS_IDS.put("KDC_DOGE", 283);
		CURRENCY_PAIRS_IDS.put("KDC_LTC", 251);
		CURRENCY_PAIRS_IDS.put("LGD_BC", 491);
		CURRENCY_PAIRS_IDS.put("LGD_BTC", 419);
		CURRENCY_PAIRS_IDS.put("LGD_DOGE", 421);
		CURRENCY_PAIRS_IDS.put("LGD_LTC", 420);
		CURRENCY_PAIRS_IDS.put("LOT_BTC", 76);
		CURRENCY_PAIRS_IDS.put("LOT_DOGE", 24);
		CURRENCY_PAIRS_IDS.put("LOT_LTC", 75);
		CURRENCY_PAIRS_IDS.put("LOVE_BTC", 495);
		CURRENCY_PAIRS_IDS.put("LOVE_DOGE", 497);
		CURRENCY_PAIRS_IDS.put("LOVE_LTC", 496);
		CURRENCY_PAIRS_IDS.put("LTC_BTC", 79);
		CURRENCY_PAIRS_IDS.put("LTC_DOGE", 25);
		CURRENCY_PAIRS_IDS.put("LVC_BTC", 467);
		CURRENCY_PAIRS_IDS.put("LVC_DOGE", 469);
		CURRENCY_PAIRS_IDS.put("LVC_LTC", 468);
		CURRENCY_PAIRS_IDS.put("LYC_BTC", 440);
		CURRENCY_PAIRS_IDS.put("LYC_DOGE", 442);
		CURRENCY_PAIRS_IDS.put("LYC_LTC", 441);
		CURRENCY_PAIRS_IDS.put("MAZA_BTC", 222);
		CURRENCY_PAIRS_IDS.put("MAZA_DOGE", 284);
		CURRENCY_PAIRS_IDS.put("MAZA_LTC", 253);
		CURRENCY_PAIRS_IDS.put("MEC_BTC", 155);
		CURRENCY_PAIRS_IDS.put("MEC_DOGE", 27);
		CURRENCY_PAIRS_IDS.put("MEC_LTC", 125);
		CURRENCY_PAIRS_IDS.put("MED_BTC", 156);
		CURRENCY_PAIRS_IDS.put("MED_DOGE", 28);
		CURRENCY_PAIRS_IDS.put("MED_LTC", 126);
		CURRENCY_PAIRS_IDS.put("MEOW_BTC", 371);
		CURRENCY_PAIRS_IDS.put("MEOW_DOGE", 373);
		CURRENCY_PAIRS_IDS.put("MEOW_LTC", 372);
		CURRENCY_PAIRS_IDS.put("METH_BC", 488);
		CURRENCY_PAIRS_IDS.put("METH_BTC", 392);
		CURRENCY_PAIRS_IDS.put("METH_DOGE", 394);
		CURRENCY_PAIRS_IDS.put("METH_LTC", 393);
		CURRENCY_PAIRS_IDS.put("MINT_BTC", 157);
		CURRENCY_PAIRS_IDS.put("MINT_DOGE", 29);
		CURRENCY_PAIRS_IDS.put("MINT_LTC", 127);
		CURRENCY_PAIRS_IDS.put("MLC_BTC", 158);
		CURRENCY_PAIRS_IDS.put("MLC_DOGE", 30);
		CURRENCY_PAIRS_IDS.put("MLC_LTC", 128);
		CURRENCY_PAIRS_IDS.put("MMC_BTC", 380);
		CURRENCY_PAIRS_IDS.put("MMC_DOGE", 382);
		CURRENCY_PAIRS_IDS.put("MMC_LTC", 381);
		CURRENCY_PAIRS_IDS.put("MOL_BTC", 159);
		CURRENCY_PAIRS_IDS.put("MOL_DOGE", 31);
		CURRENCY_PAIRS_IDS.put("MOL_LTC", 129);
		CURRENCY_PAIRS_IDS.put("MOON_BTC", 77);
		CURRENCY_PAIRS_IDS.put("MOON_DOGE", 32);
		CURRENCY_PAIRS_IDS.put("MOON_LTC", 74);
		CURRENCY_PAIRS_IDS.put("MRS_BTC", 498);
		CURRENCY_PAIRS_IDS.put("MRS_DOGE", 500);
		CURRENCY_PAIRS_IDS.put("MRS_LTC", 499);
		CURRENCY_PAIRS_IDS.put("MYR_BTC", 422);
		CURRENCY_PAIRS_IDS.put("MYR_DOGE", 424);
		CURRENCY_PAIRS_IDS.put("MYR_LTC", 423);
		CURRENCY_PAIRS_IDS.put("NET_BTC", 160);
		CURRENCY_PAIRS_IDS.put("NET_DOGE", 33);
		CURRENCY_PAIRS_IDS.put("NET_LTC", 130);
		CURRENCY_PAIRS_IDS.put("NOBL_BTC", 359);
		CURRENCY_PAIRS_IDS.put("NOBL_DOGE", 361);
		CURRENCY_PAIRS_IDS.put("NOBL_LTC", 360);
		CURRENCY_PAIRS_IDS.put("NUT_BC", 489);
		CURRENCY_PAIRS_IDS.put("NUT_BTC", 202);
		CURRENCY_PAIRS_IDS.put("NUT_DOGE", 204);
		CURRENCY_PAIRS_IDS.put("NUT_LTC", 203);
		CURRENCY_PAIRS_IDS.put("NYAN_BTC", 223);
		CURRENCY_PAIRS_IDS.put("NYAN_DOGE", 285);
		CURRENCY_PAIRS_IDS.put("NYAN_LTC", 254);
		CURRENCY_PAIRS_IDS.put("OFF_BTC", 224);
		CURRENCY_PAIRS_IDS.put("OFF_DOGE", 286);
		CURRENCY_PAIRS_IDS.put("OFF_LTC", 255);
		CURRENCY_PAIRS_IDS.put("OLY_BTC", 383);
		CURRENCY_PAIRS_IDS.put("OLY_DOGE", 385);
		CURRENCY_PAIRS_IDS.put("OLY_LTC", 384);
		CURRENCY_PAIRS_IDS.put("ORCA_BTC", 431);
		CURRENCY_PAIRS_IDS.put("ORCA_DOGE", 433);
		CURRENCY_PAIRS_IDS.put("ORCA_LTC", 432);
		CURRENCY_PAIRS_IDS.put("PAWN_BTC", 404);
		CURRENCY_PAIRS_IDS.put("PAWN_DOGE", 406);
		CURRENCY_PAIRS_IDS.put("PAWN_LTC", 405);
		CURRENCY_PAIRS_IDS.put("PD_BTC", 464);
		CURRENCY_PAIRS_IDS.put("PD_DOGE", 466);
		CURRENCY_PAIRS_IDS.put("PD_LTC", 465);
		CURRENCY_PAIRS_IDS.put("PIR_BTC", 161);
		CURRENCY_PAIRS_IDS.put("PIR_DOGE", 10);
		CURRENCY_PAIRS_IDS.put("PIR_LTC", 9);
		CURRENCY_PAIRS_IDS.put("PKC_BTC", 162);
		CURRENCY_PAIRS_IDS.put("PKC_DOGE", 35);
		CURRENCY_PAIRS_IDS.put("PKC_LTC", 131);
		CURRENCY_PAIRS_IDS.put("PLC_BTC", 329);
		CURRENCY_PAIRS_IDS.put("PLC_DOGE", 331);
		CURRENCY_PAIRS_IDS.put("PLC_LTC", 330);
		CURRENCY_PAIRS_IDS.put("PMC_BTC", 225);
		CURRENCY_PAIRS_IDS.put("PMC_DOGE", 287);
		CURRENCY_PAIRS_IDS.put("PMC_LTC", 256);
		CURRENCY_PAIRS_IDS.put("POP_BTC", 368);
		CURRENCY_PAIRS_IDS.put("POP_DOGE", 370);
		CURRENCY_PAIRS_IDS.put("POP_LTC", 369);
		CURRENCY_PAIRS_IDS.put("POT_BTC", 226);
		CURRENCY_PAIRS_IDS.put("POT_DOGE", 288);
		CURRENCY_PAIRS_IDS.put("POT_LTC", 257);
		CURRENCY_PAIRS_IDS.put("PPC_BTC", 407);
		CURRENCY_PAIRS_IDS.put("PPC_DOGE", 409);
		CURRENCY_PAIRS_IDS.put("PPC_LTC", 408);
		CURRENCY_PAIRS_IDS.put("PRC_BTC", 461);
		CURRENCY_PAIRS_IDS.put("PRC_DOGE", 463);
		CURRENCY_PAIRS_IDS.put("PRC_LTC", 462);
		CURRENCY_PAIRS_IDS.put("PRT_BTC", 163);
		CURRENCY_PAIRS_IDS.put("PRT_DOGE", 36);
		CURRENCY_PAIRS_IDS.put("PRT_LTC", 132);
		CURRENCY_PAIRS_IDS.put("PTC_BTC", 175);
		CURRENCY_PAIRS_IDS.put("PTC_DOGE", 173);
		CURRENCY_PAIRS_IDS.put("PTC_LTC", 174);
		CURRENCY_PAIRS_IDS.put("PT_BTC", 416);
		CURRENCY_PAIRS_IDS.put("PT_DOGE", 418);
		CURRENCY_PAIRS_IDS.put("PT_LTC", 417);
		CURRENCY_PAIRS_IDS.put("PXC_BTC", 320);
		CURRENCY_PAIRS_IDS.put("PXC_DOGE", 322);
		CURRENCY_PAIRS_IDS.put("PXC_LTC", 321);
		CURRENCY_PAIRS_IDS.put("Q2C_BTC", 227);
		CURRENCY_PAIRS_IDS.put("Q2C_DOGE", 289);
		CURRENCY_PAIRS_IDS.put("Q2C_LTC", 258);
		CURRENCY_PAIRS_IDS.put("QQC_BTC", 164);
		CURRENCY_PAIRS_IDS.put("QQC_DOGE", 37);
		CURRENCY_PAIRS_IDS.put("QQC_LTC", 133);
		CURRENCY_PAIRS_IDS.put("QRK_BTC", 228);
		CURRENCY_PAIRS_IDS.put("QRK_DOGE", 290);
		CURRENCY_PAIRS_IDS.put("QRK_LTC", 259);
		CURRENCY_PAIRS_IDS.put("RDD_BTC", 165);
		CURRENCY_PAIRS_IDS.put("RDD_DOGE", 38);
		CURRENCY_PAIRS_IDS.put("RDD_LTC", 134);
		CURRENCY_PAIRS_IDS.put("RUP_BTC", 473);
		CURRENCY_PAIRS_IDS.put("RUP_DOGE", 475);
		CURRENCY_PAIRS_IDS.put("RUP_LTC", 474);
		CURRENCY_PAIRS_IDS.put("SLR_BC", 486);
		CURRENCY_PAIRS_IDS.put("SLR_BTC", 229);
		CURRENCY_PAIRS_IDS.put("SLR_DOGE", 291);
		CURRENCY_PAIRS_IDS.put("SLR_LTC", 260);
		CURRENCY_PAIRS_IDS.put("SMC_BTC", 230);
		CURRENCY_PAIRS_IDS.put("SMC_DOGE", 292);
		CURRENCY_PAIRS_IDS.put("SMC_LTC", 261);
		CURRENCY_PAIRS_IDS.put("SOC_BTC", 377);
		CURRENCY_PAIRS_IDS.put("SOC_DOGE", 379);
		CURRENCY_PAIRS_IDS.put("SOC_LTC", 378);
		CURRENCY_PAIRS_IDS.put("STL_BC", 490);
		CURRENCY_PAIRS_IDS.put("STL_BTC", 305);
		CURRENCY_PAIRS_IDS.put("STL_DOGE", 307);
		CURRENCY_PAIRS_IDS.put("STL_LTC", 306);
		CURRENCY_PAIRS_IDS.put("STP_BTC", 501);
		CURRENCY_PAIRS_IDS.put("STP_DOGE", 503);
		CURRENCY_PAIRS_IDS.put("STP_LTC", 502);
		CURRENCY_PAIRS_IDS.put("SXC_BTC", 78);
		CURRENCY_PAIRS_IDS.put("SXC_DOGE", 39);
		CURRENCY_PAIRS_IDS.put("SXC_LTC", 135);
		CURRENCY_PAIRS_IDS.put("TFC_BTC", 231);
		CURRENCY_PAIRS_IDS.put("TFC_DOGE", 293);
		CURRENCY_PAIRS_IDS.put("TFC_LTC", 262);
		CURRENCY_PAIRS_IDS.put("TGC_BTC", 350);
		CURRENCY_PAIRS_IDS.put("TGC_DOGE", 352);
		CURRENCY_PAIRS_IDS.put("TGC_LTC", 351);
		CURRENCY_PAIRS_IDS.put("TIPS_BTC", 191);
		CURRENCY_PAIRS_IDS.put("TIPS_DOGE", 193);
		CURRENCY_PAIRS_IDS.put("TIPS_LTC", 192);
		CURRENCY_PAIRS_IDS.put("TOP_BTC", 185);
		CURRENCY_PAIRS_IDS.put("TOP_DOGE", 187);
		CURRENCY_PAIRS_IDS.put("TOP_LTC", 186);
		CURRENCY_PAIRS_IDS.put("TTC_BTC", 446);
		CURRENCY_PAIRS_IDS.put("TTC_DOGE", 448);
		CURRENCY_PAIRS_IDS.put("TTC_LTC", 447);
		CURRENCY_PAIRS_IDS.put("UNC_BTC", 166);
		CURRENCY_PAIRS_IDS.put("UNC_DOGE", 41);
		CURRENCY_PAIRS_IDS.put("UNC_LTC", 136);
		CURRENCY_PAIRS_IDS.put("USDE_BTC", 179);
		CURRENCY_PAIRS_IDS.put("USDE_DOGE", 181);
		CURRENCY_PAIRS_IDS.put("USDE_LTC", 180);
		CURRENCY_PAIRS_IDS.put("UTC_BTC", 167);
		CURRENCY_PAIRS_IDS.put("UTC_DOGE", 42);
		CURRENCY_PAIRS_IDS.put("UTC_LTC", 137);
		CURRENCY_PAIRS_IDS.put("VEL_BTC", 311);
		CURRENCY_PAIRS_IDS.put("VEL_DOGE", 313);
		CURRENCY_PAIRS_IDS.put("VEL_LTC", 312);
		CURRENCY_PAIRS_IDS.put("VGC_BTC", 425);
		CURRENCY_PAIRS_IDS.put("VGC_DOGE", 427);
		CURRENCY_PAIRS_IDS.put("VGC_LTC", 426);
		CURRENCY_PAIRS_IDS.put("VMP_BTC", 437);
		CURRENCY_PAIRS_IDS.put("VMP_DOGE", 439);
		CURRENCY_PAIRS_IDS.put("VMP_LTC", 438);
		CURRENCY_PAIRS_IDS.put("VTC_BTC", 232);
		CURRENCY_PAIRS_IDS.put("VTC_DOGE", 294);
		CURRENCY_PAIRS_IDS.put("VTC_LTC", 263);
		CURRENCY_PAIRS_IDS.put("WDC_BTC", 365);
		CURRENCY_PAIRS_IDS.put("WDC_DOGE", 367);
		CURRENCY_PAIRS_IDS.put("WDC_LTC", 366);
		CURRENCY_PAIRS_IDS.put("WTC_BTC", 233);
		CURRENCY_PAIRS_IDS.put("WTC_DOGE", 295);
		CURRENCY_PAIRS_IDS.put("WTC_LTC", 264);
		CURRENCY_PAIRS_IDS.put("XTN_BTC", 504);
		CURRENCY_PAIRS_IDS.put("XTN_DOGE", 506);
		CURRENCY_PAIRS_IDS.put("XTN_LTC", 505);
		CURRENCY_PAIRS_IDS.put("XXL_BTC", 302);
		CURRENCY_PAIRS_IDS.put("XXL_DOGE", 304);
		CURRENCY_PAIRS_IDS.put("XXL_LTC", 303);
		CURRENCY_PAIRS_IDS.put("ZMB_BTC", 443);
		CURRENCY_PAIRS_IDS.put("ZMB_DOGE", 445);
		CURRENCY_PAIRS_IDS.put("ZMB_LTC", 444);
		CURRENCY_PAIRS_IDS.put("ZTC_BTC", 452);
		CURRENCY_PAIRS_IDS.put("ZTC_DOGE", 454);
		CURRENCY_PAIRS_IDS.put("ZTC_LTC", 453);
	}
	
	public AllCrypt() {
		super(NAME, TTS_NAME, CURRENCY_PAIRS);
	}

	@Override
	public String getUrl(int requestId, CheckerInfo checkerInfo) {
		final String pairString = String.format("%1$s_%2$s", checkerInfo.getCurrencyBase(), checkerInfo.getCurrencyCounter());
		if(CURRENCY_PAIRS_IDS.containsKey(pairString))
			return String.format(URL, String.valueOf(CURRENCY_PAIRS_IDS.get(pairString)));	
		return String.format(URL, checkerInfo.getCurrencyPairId());
	}
	
	@Override
	protected void parseTickerFromJsonObject(int requestId, JSONObject jsonObject, Ticker ticker, CheckerInfo checkerInfo) throws Exception {
		final JSONObject returnObject = jsonObject.getJSONObject("return");
		final JSONObject marketsObject = returnObject.getJSONObject("markets");
		final JSONObject pairObject = marketsObject.getJSONObject(marketsObject.names().getString(0));
		
		ticker.bid = getFirstPriceFromOrdersArray(pairObject.optJSONArray("buyorders"));
		ticker.ask = getFirstPriceFromOrdersArray(pairObject.optJSONArray("sellorders"));
		ticker.vol = pairObject.getDouble("volume");
//		ticker.high;
//		ticker.low;
		ticker.last = pairObject.getDouble("lasttradeprice");
//		ticker.timestamp;
	}
	
	private double getFirstPriceFromOrdersArray(JSONArray ordersArray) {
		try {
			if(ordersArray!=null && ordersArray.length()>0) {
				final JSONObject jsonObject = ordersArray.optJSONObject(0);
				if(jsonObject!=null)
					return jsonObject.getDouble("price");
			}
		} catch (Exception e) {
			e.printStackTrace();
		}
		return Ticker.NO_DATA;
	}
	
	// ====================
	// Get currency pairs
	// ====================
	@Override
	public String getCurrencyPairsUrl() {
		return URL_CURRENCY_PAIRS;
	}
	
	@Override
	protected void parseCurrencyPairsFromJsonObject(JSONObject jsonObject, List<CurrencyPairInfo> pairs) throws Exception {
		final JSONObject returnObject = jsonObject.getJSONObject("return");
		final JSONObject marketsObject = returnObject.getJSONObject("markets");
		final JSONArray marketNames = marketsObject.names();
		
		for(int i=0; i<marketNames.length(); ++i) {
			JSONObject marketObject = marketsObject.getJSONObject(marketNames.getString(i));
			pairs.add(new CurrencyPairInfo(
					marketObject.getString("primarycode"),
					marketObject.getString("secondarycode"),
					marketObject.getString("marketid")
				));
		}
	}
}
