package com.aneonex.bitcoinchecker.datamodule.model.currency

object CurrencySymbols {
    val CURRENCY_SYMBOLS = mapOf(
        Currency.USD to "$",
        Currency.PLN to "zł",
        Currency.CNY to "¥",
        Currency.EUR to "€",
//		CURRENCY_SYMBOLS.put(CAD, "$"),
        Currency.GBP to "£",
        Currency.CHF to "Fr",
        Currency.RUB to "₽",
        Currency.RUR to "₽",
//        Currency.AUD to "$",
        Currency.SEK to "kr",
        Currency.DKK to "kr",
//        Currency.HKD to "$",
//        Currency.SGD to "$",
        Currency.THB to "฿",
//        Currency.NZD to "$",
        Currency.JPY to "¥",
        Currency.BRL to "R$",
        Currency.KRW to "₩",
        Currency.AFN to "؋",
        Currency.ALL to "L",
        Currency.DZD to "د.ج",
        Currency.AOA to "Kz",
//        Currency.ARS to "$",
        Currency.AMD to "֏",
        Currency.AWG to "ƒ",
        Currency.AZN to "m",
//        Currency.BSD to "$",
        Currency.BHD to "ب.د",
        Currency.BDT to "৳",
//        Currency.BBD to "$",
        Currency.BYR to "Br",
//        Currency.BZD to "$",
//        Currency.BMD to "$",
        Currency.BTN to "Nu.",
        Currency.BOB to "Bs.",
        Currency.BAM to "КМ",
        Currency.BWP to "P",
//        Currency.BND to "$",
        Currency.BGN to "лв",
        Currency.BIF to "Fr",
        Currency.TRY to "TL",
        Currency.ZAR to "R",
        Currency.IDR to "Rp",
//        Currency.VND to "₫",
        Currency.GEL to "₾",
//        Currency.IRR to "﷼",
        Currency.HUF to "Ft",
//        Currency.ILS to "₪",
        Currency.INR to "₹",
        Currency.JOD to "JD",
        Currency.ISK to "kr",
        Currency.KZT to "₸",
//        Currency.KHR to "៛",
//        Currency.QAR to "﷼",
        Currency.KES to "KSH",
//        Currency.KGS to "с",
        Currency.CRC to "₡",
        Currency.CHF to "₣",
        Currency.MYR to "RM",
        Currency.MAD to "Dh",
        Currency.MNT to "₮",
        Currency.NGN to "₦",
        Currency.AED to "Dh",
        Currency.PEN to "S/",
        Currency.RON to "L",
        Currency.SAR to "SR",
        Currency.RSD to "din.",
        Currency.TZS to "TSh",
//        Currency.UAH to "₴",
        Currency.PHP to "₱",
        Currency.CZK to "Kč",
    )
}