package com.aneonex.bitcoinchecker.datamodule.model.currency

import java.util.*

object CurrencySymbols {
    val CURRENCY_SYMBOLS = HashMap<String, String>()

    init {
        CURRENCY_SYMBOLS[Currency.USD] = "$"
        CURRENCY_SYMBOLS[Currency.PLN] = "zł"
        CURRENCY_SYMBOLS[Currency.CNY] = "¥"
        CURRENCY_SYMBOLS[Currency.EUR] = "€"
        //		CURRENCY_SYMBOLS.put(CAD, "$");
        CURRENCY_SYMBOLS[Currency.GBP] = "£"
        CURRENCY_SYMBOLS[Currency.CHF] = "Fr"
        CURRENCY_SYMBOLS[Currency.RUB] = "₽"
        CURRENCY_SYMBOLS[Currency.RUR] = "₽"
//        CURRENCY_SYMBOLS[Currency.AUD] = "$"
        CURRENCY_SYMBOLS[Currency.SEK] = "kr"
        CURRENCY_SYMBOLS[Currency.DKK] = "kr"
//        CURRENCY_SYMBOLS[Currency.HKD] = "$"
//        CURRENCY_SYMBOLS[Currency.SGD] = "$"
        CURRENCY_SYMBOLS[Currency.THB] = "฿"
//        CURRENCY_SYMBOLS[Currency.NZD] = "$"
        CURRENCY_SYMBOLS[Currency.JPY] = "¥"
        CURRENCY_SYMBOLS[Currency.BRL] = "R$"
        CURRENCY_SYMBOLS[Currency.KRW] = "₩"
        CURRENCY_SYMBOLS[Currency.AFN] = "؋"
        CURRENCY_SYMBOLS[Currency.ALL] = "L"
        CURRENCY_SYMBOLS[Currency.DZD] = "د.ج"
        CURRENCY_SYMBOLS[Currency.AOA] = "Kz"
//        CURRENCY_SYMBOLS[Currency.ARS] = "$"
        CURRENCY_SYMBOLS[Currency.AMD] = "֏"
        CURRENCY_SYMBOLS[Currency.AWG] = "ƒ"
        CURRENCY_SYMBOLS[Currency.AZN] = "m"
//        CURRENCY_SYMBOLS[Currency.BSD] = "$"
        CURRENCY_SYMBOLS[Currency.BHD] = "ب.د"
        CURRENCY_SYMBOLS[Currency.BDT] = "৳"
//        CURRENCY_SYMBOLS[Currency.BBD] = "$"
        CURRENCY_SYMBOLS[Currency.BYR] = "Br"
//        CURRENCY_SYMBOLS[Currency.BZD] = "$"
//        CURRENCY_SYMBOLS[Currency.BMD] = "$"
        CURRENCY_SYMBOLS[Currency.BTN] = "Nu."
        CURRENCY_SYMBOLS[Currency.BOB] = "Bs."
        CURRENCY_SYMBOLS[Currency.BAM] = "КМ"
        CURRENCY_SYMBOLS[Currency.BWP] = "P"
//        CURRENCY_SYMBOLS[Currency.BND] = "$"
        CURRENCY_SYMBOLS[Currency.BGN] = "лв"
        CURRENCY_SYMBOLS[Currency.BIF] = "Fr"
        CURRENCY_SYMBOLS[Currency.TRY] = "TL"
        CURRENCY_SYMBOLS[Currency.ZAR] = "R"
        CURRENCY_SYMBOLS[Currency.IDR] = "Rp"
//        CURRENCY_SYMBOLS[Currency.VND] = "₫"
        CURRENCY_SYMBOLS[Currency.GEL] = "₾"
//        CURRENCY_SYMBOLS[Currency.IRR] = "﷼"
        CURRENCY_SYMBOLS[Currency.HUF] = "Ft"
//        CURRENCY_SYMBOLS[Currency.ILS] = "₪"
        CURRENCY_SYMBOLS[Currency.INR] = "₹"
        CURRENCY_SYMBOLS[Currency.JOD] = "JD"
        CURRENCY_SYMBOLS[Currency.ISK] = "kr"
        CURRENCY_SYMBOLS[Currency.KZT] = "₸"
//        CURRENCY_SYMBOLS[Currency.KHR] = "៛"
//        CURRENCY_SYMBOLS[Currency.QAR] = "﷼"
        CURRENCY_SYMBOLS[Currency.KES] = "KSH"
//        CURRENCY_SYMBOLS[Currency.KGS] = "с"
        CURRENCY_SYMBOLS[Currency.CRC] = "₡"
        CURRENCY_SYMBOLS[Currency.CHF] = "₣"
        CURRENCY_SYMBOLS[Currency.MYR] = "RM"
        CURRENCY_SYMBOLS[Currency.MAD] = "Dh"
        CURRENCY_SYMBOLS[Currency.MNT] = "₮"
        CURRENCY_SYMBOLS[Currency.NGN] = "₦"
        CURRENCY_SYMBOLS[Currency.AED] = "Dh"
        CURRENCY_SYMBOLS[Currency.PEN] = "S/"
        CURRENCY_SYMBOLS[Currency.RON] = "L"
        CURRENCY_SYMBOLS[Currency.SAR] = "SR"
        CURRENCY_SYMBOLS[Currency.RSD] = "din."
        CURRENCY_SYMBOLS[Currency.TZS] = "TSh"
//        CURRENCY_SYMBOLS[Currency.UAH] = "₴"
        CURRENCY_SYMBOLS[Currency.PHP] = "₱"
        CURRENCY_SYMBOLS[Currency.CZK] = "Kč"
    }
}